# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Required permissions that must be set in caller workflows (in private repositories):
# contents: (read)      for actions/checkout to fetch code (included in 'write')
# contents: write       for advanced-security/maven-dependency-submission-action to submit dependencies

name: Maven Project Build

on:
  workflow_call:
    inputs:
      checkout_ref:
        description: The branch to checkout - see https://github.com/actions/checkout#usage (ref).
        type: string
        required: false
      java_version:
        description: The Java version to be used - see https://github.com/actions/setup-java#usage (java-version).
        type: string
        required: false
        default: 11
      java_distribution:
        description: The Java distribution to be used - see https://github.com/actions/setup-java#usage (distribution).
        type: string
        required: false
        default: corretto
      maven_cache_key_prefix:
        description: |
          A custom cache key prefix for the local Maven repository. By default, the workflow uses the optimized cache
          implementation of the 'setup_java' action - see https://github.com/actions/setup-java#usage (cache). When
          a custom cache key prefix is provided, it uses the 'cache' action directly and configures the key with the
          custom prefix instead of the 'setup-java' prefix - https://github.com/actions/cache#inputs (key). Please note
          that no 'restore-keys' optimization applies in this case.
        type: string
        required: false
      maven_command:
        description: The Maven build command to be executed.
        type: string
        required: false
        default: 'mvn --batch-mode install'
      maven_settings:
        description: |
          The (user) 'settings.xml' file to be used for the Maven build. Environment variables for replacement tokens
          (like '${env.MY_USERNAME}') in the 'settings.xml' can be provided as secrets with the same name. They will
          internally be provided as environment variables to the build environment.
          Hint: Use 'secrets: inherit' to provide the secrets from the caller workflow's repository settings to the
          reusable workflow without having to map them one by one.
        type: string
        required: false
      skip_update_dependency_graph:
        description: |
          Allows to skip the upload of the full dependency graph to GitHub. By default, the full dependency graph is
          uploaded to GitHub when this Maven workflow is executed on the default branch of the repository, in order to
          improve the quality of Dependabot alerts. This upload can be skipped, e.g. when executing the workflow with
          a build configuration that would lead to an unwanted or invalid dependency graph being uploaded. On the other
          hand, enforcing the upload for non-default branches is not possible as it won't make sense.
        type: boolean
        required: false
        default: false
    outputs:
      teams_fact_json:
        description: The 'fact' JSON snippet that can be added to an MS Teams Notification.
        value: |
          {
            "name": "Maven Build:",
            "value": "${{ jobs.maven.outputs.result }}"
          }

jobs:
  maven:
    name: Maven Build
    runs-on: ubuntu-latest
    outputs:
      result: ${{ job.status }}

    steps:
      - name: Provide secrets to build environment
        uses: oNaiPs/secrets-to-env-action@v1.3
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ inputs.checkout_ref }}

      - name: Initialize internal configuration
        id: config
        run: |
          if [[ -n '${{ inputs.checkout_ref }}' ]]; then
            echo "checkout_ref=${{ inputs.checkout_ref }}" >> "$GITHUB_OUTPUT"
          else
            echo "checkout_ref=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: ${{ inputs.java_version }}
          distribution: ${{ inputs.java_distribution }}
          cache: ${{ (!env.ACT && !inputs.maven_cache_key_prefix) && 'maven' || '' }}

      - name: Cache Maven Repo with custom key (replacing cache from Set up JDK)
        if: ${{ !env.ACT && inputs.maven_cache_key_prefix }}
        uses: actions/cache@v3.3.2
        with:
          path: ~/.m2/repository
          key: ${{ inputs.maven_cache_key_prefix }}-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Overwrite Maven settings
        if: inputs.maven_settings
        run: cp ${{ inputs.maven_settings }} ${HOME}/.m2/settings.xml

      - name: Run Maven Build
        run: ${{ inputs.maven_command }}

      - name: Update dependency graph
        if: (!inputs.skip_update_dependency_graph) && steps.config.outputs.checkout_ref == github.event.repository.default_branch
        uses: advanced-security/maven-dependency-submission-action@v3.0.3
