# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Required permissions that must be set in caller workflows (in private repositories):
# contents: (read)      for actions/checkout to fetch code (included in 'write')
# contents: write       for advanced-security/maven-dependency-submission-action to submit dependencies

name: Maven Project Build

on:
  workflow_call:
    inputs:
      checkout_ref:
        description: The branch to checkout - see https://github.com/actions/checkout#usage (ref).
        type: string
        required: false
      java_version:
        description: The Java version to be used - see https://github.com/actions/setup-java#usage (java-version).
        type: string
        required: false
        default: 11
      java_distribution:
        description: The Java distribution to be used - see https://github.com/actions/setup-java#usage (distribution).
        type: string
        required: false
        default: corretto
      maven_cache_key_prefix:
        description: |
          A custom cache key prefix for the local Maven repository. By default, the workflow uses the optimized cache
          implementation of the 'setup_java' action - see https://github.com/actions/setup-java#usage (cache). When
          a custom cache key prefix is provided, it uses the 'cache' action directly and configures the key with the
          custom prefix instead of the 'setup-java' prefix - https://github.com/actions/cache#inputs (key). Please note
          that no 'restore-keys' optimization applies in this case.
        type: string
        required: false
      maven_command:
        description: The Maven build command to be executed.
        type: string
        required: false
        default: 'mvn --batch-mode install'
      maven_repo_server_id:
        description: The ID of an additional Maven repository to download artifacts from.
        type: string
        required: false
        default: ''
      maven_settings:
        description: |
          The (user) 'settings.xml' file to be used for the Maven build. When provided, it will supersede the input
          'maven_repo_server_id'. Please note that environment variables cannot be provided from the caller workflow.
          If environment variables with server credentials are required by the provided 'settings.xml', they must be
          named 'MAVEN_REPO_USER' and 'MAVEN_REPO_PASSWORD' and have to be set via workflow secrets 'maven_repo_user'
          and 'maven_repo_password'.
        type: string
        required: false
        default: ''
    secrets:
      maven_repo_user:
        description: |
          The user to connect to an additional Maven repository to download artifacts from. Will be set via
          environment variable 'MAVEN_REPO_USER'.
        required: false
      maven_repo_password:
        description: |
          The password to connect to an additional Maven repository to download artifacts from. Will be set
          via environment variable 'MAVEN_REPO_PASSWORD'.
        required: false
    outputs:
      teams_fact_json:
        description: The 'fact' JSON snippet that can be added to an MS Teams Notification.
        value: |
          {
            "name": "Maven Build:",
            "value": "${{ jobs.maven.outputs.result }}"
          }

jobs:
  maven:
    name: Maven Build
    runs-on: ubuntu-latest
    env:
      MAVEN_REPO_USER: ${{ secrets.maven_repo_user }}
      MAVEN_REPO_PASSWORD: ${{ secrets.maven_repo_password }}
    outputs:
      result: ${{ job.status }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3
        with:
          ref: ${{ inputs.checkout_ref }}

      - name: Initialize internal configuration
        id: config
        run: |
          if [[ -n '${{ inputs.checkout_ref }}' ]]; then
            echo "checkout_ref=${{ inputs.checkout_ref }}" >> "$GITHUB_OUTPUT"
          else
            echo "checkout_ref=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Set up JDK
        uses: actions/setup-java@v3.12.0
        with:
          java-version: ${{ inputs.java_version }}
          distribution: ${{ inputs.java_distribution }}
          server-id: ${{ inputs.maven_repo_server_id }}
          server-username: MAVEN_REPO_USER
          server-password: MAVEN_REPO_PASSWORD
          cache: ${{ (!env.ACT && !inputs.maven_cache_key_prefix) && 'maven' || '' }}

      - name: Cache Maven Repo with custom key (replacing cache from Set up JDK)
        if: ${{ !env.ACT && inputs.maven_cache_key_prefix }}
        uses: actions/cache@v3.3.1
        with:
          path: ~/.m2/repository
          key: ${{ inputs.maven_cache_key_prefix }}-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Overwrite Maven settings
        if: inputs.maven_settings
        run: cp ${{ inputs.maven_settings }} ${HOME}/.m2/settings.xml

      - name: Run Maven Build
        run: ${{ inputs.maven_command }}

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive.
      - name: Update dependency graph
        if: steps.config.outputs.checkout_ref == github.event.repository.default_branch
        uses: advanced-security/maven-dependency-submission-action@v3.0.2
