# *********************** DEPRECATED WORKFLOW *********************** #
#    This workflow is deprecated and will be removed in the future.   #
#          See also the information in the project's README.          #
# *********************** DEPRECATED WORKFLOW *********************** #

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MS Teams Notifications

on:
  workflow_call:
    inputs:
      workflow:
        description: The name of the workflow to send the notification for.
        type: string
        required: true
      run_id:
        description: The ID of the job run to send the notification for.
        type: string
        required: true
      run_result:
        description: |
          The result of the job run to send the notification for - 'success', 'failure' or 'cancelled'.
        type: string
        required: true
      facts_json:
        description: |
          The facts JSON array fragment for message sections - see
          https://github.com/aliencube/microsoft-teams-actions/blob/dev/README.md#inputs (sections) and
          https://learn.microsoft.com/en-us/outlook/actionable-messages/message-card-reference#section-fields.
        type: string
        required: false
        default: '{}'
    secrets:
      webhook:
        description: |
          The incoming webhook URI to Microsoft Teams - see
          https://github.com/aliencube/microsoft-teams-actions/blob/dev/README.md#inputs (webhook_uri).
        required: true

jobs:
  teams:
    name: Send Notification
    runs-on: ubuntu-latest

    steps:
      - name: Initialize internal configuration
        id: config
        run: |
          case '${{ inputs.run_result }}' in
            success)
              echo 'summary=Workflow **${{ inputs.workflow }}** finished successfully.' >> "$GITHUB_OUTPUT"
              echo 'theme_color=05b222' >> "$GITHUB_OUTPUT"
              ;;
            cancelled)
              echo 'summary=Workflow **${{ inputs.workflow }}** was cancelled.' >> "$GITHUB_OUTPUT"
              echo 'theme_color=949393' >> "$GITHUB_OUTPUT"
              ;;
            failure)
              echo 'summary=Workflow **${{ inputs.workflow }}** failed.' >> "$GITHUB_OUTPUT"
              echo 'theme_color=d9534f' >> "$GITHUB_OUTPUT"
              ;;
            *)
              echo "::error title=Configuration Error::'run_result=${{ inputs.run_result }}' but must be one of 'success', 'failure' or 'cancelled'."
              exit 1
              ;;
          esac

      - name: Send notification the MS Teams Webhook
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.webhook }}
          summary: ${{ steps.config.outputs.summary }}
          theme_color: ${{ steps.config.outputs.theme_color }}
          sections: |
            [
              {
                "activityTitle": "Notification from ${{ github.repository }}",
                "activitySubtitle": "${{ steps.config.outputs.summary }}",
                "facts": ${{ inputs.facts_json }}
              }
            ]
          actions: |
            [
              {
                "@type": "OpenUri", "name": "View Workflow Run",
                "targets": [
                  { "os": "default", "uri": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ inputs.run_id }}" }
                ]
              }
            ]
